# Generated by Django 4.1.11 on 2023-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Не указанно', max_length=228)),
                ('main_photo_path', models.TextField(default='Не указанно', max_length=1028)),
                ('description', models.TextField(default='Не указанно', max_length=1028)),
                ('manufacturer', models.TextField(default='Не указанно', max_length=1028)),
                ('orign_country', models.TextField(default='Не указанно', max_length=1028)),
                ('brand', models.TextField(default='Не указанно', max_length=1028)),
                ('opt_price', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('unit', models.TextField(default='Не указанно', max_length=228)),
                ('unit_storage', models.TextField(default='Не указанно', max_length=228)),
                ('weight', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
            ],
        ),
    ]
