# Generated by Django 4.1.11 on 2023-09-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='colors',
            field=models.TextField(default='Не указанно'),
        ),
        migrations.AddField(
            model_name='position',
            name='colors_photo_path',
            field=models.TextField(default='Не указанно'),
        ),
    ]
