# Generated by Django 4.1.11 on 2023-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_position_colors_position_colors_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='colors',
            field=models.TextField(default='Стандартный'),
        ),
        migrations.AlterField(
            model_name='position',
            name='colors_photo_path',
            field=models.TextField(default='None'),
        ),
    ]
