# Generated by Django 4.1.10 on 2023-09-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_position_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='category',
            field=models.TextField(default='Не указанно', max_length=1028),
        ),
    ]
